// =============================================================================
// constants/ypn-landing.ts
//
// ALL copy + data for the public "Yield Payment Network" (YPN) marketing surface
// (route: /yield-payment-network, plus the embeddable YieldPaymentNetworkSection).
//
// This is a TOP-OF-FUNNEL marketing surface only — no authenticated app state.
//
// HONESTY FRAMING (see .claude/rules — docs/product/framing-and-messaging.md):
// The reputation-weighted vaults (ULV) are BUILT & TESTED, in testing ahead of
// launch — never described as "live" or "deposit now". Circle Programmable
// Wallets / CCTP is the DESIGNED settlement rail, not a shipped integration.
// Attribution is live on Base. Copy here is calibrated accordingly: the network
// is presented as the mechanism/design under an explicit "in testing" status.
// =============================================================================

export const YPN_STATUS = {
  label: 'In testing ahead of launch',
  note: 'The Unified Liquidity Vault and the Yield Payment Network are built and in testing on testnet. Attribution is live on Base today. Nothing here is an offer to deposit.',
} as const

export const YPN_HERO = {
  eyebrow: 'Mintware Yield Payment Network',
  // Kept punchy but the sub-head grounds it honestly.
  title: 'Liquidity Vault Payment Magic',
  titleAccent: 'Turn passive yield into growth runway.',
  sub: 'Stop burning treasury reserves or inflating your native token on short-term marketing. Park single-sided USDC in a Unified Liquidity Vault, keep your principal intact, and route the yield it earns into user acquisition, referral rewards, and campaign payouts — attributed on-chain.',
  primaryCta: 'Launch app',
  secondaryCta: 'See how it works',
  secondaryHref: '#how-it-works',
} as const

export const YPN_INTRO = {
  eyebrow: 'What it is',
  title: 'Yield becomes a payment rail — not a passive APY number',
  body: [
    'The Yield Payment Network (YPN) is designed to turn yield from a passive, speculative metric into programmable incentive rails. Instead of spending down principal to fund growth, a treasury routes the real return generated by its locked collateral into targeted incentives and automated distribution.',
    'The premise is simple: your principal stays intact and secured inside the vault, while the yield it generates powers marketing, referral rewards, user bounties, and campaign payouts.',
  ],
} as const

// Mintware's founding ethos — "Liquidity should be a public good." YPN is the
// clearest expression of it: pooled liquidity funds a shared, self-renewing
// growth commons instead of being burned down by any single project.
export const YPN_ETHOS = {
  eyebrow: '✴ Liquidity as a public good',
  title: 'Liquidity that funds the commons, not the burn',
  body: 'Mintware exists to make liquidity a public good. YPN is that idea made concrete: capital is pooled once and kept whole, and the yield it produces becomes a shared, self-renewing fund for the growth of the whole ecosystem — builders, affiliates, and users — rather than a treasury reserve any one project spends down and never sees again. Provide liquidity once; let its yield pay forward, permissionlessly.',
  quote: 'Liquidity should be a public good.',
} as const

// ─── Architecture flow (PillarArchitectureDiagram) ──────────────────────────
export const YPN_FLOW = {
  eyebrow: 'The flow',
  title: 'From single-sided USDC to attributed payouts',
  steps: [
    {
      key: 'deposit',
      label: 'USDC Deposit',
      sub: 'Single-sided · Circle CCTP',
      desc: 'Treasuries and LPs deposit single-sided USDC, designed to route cross-chain over Circle’s CCTP rails.',
      accent: 'text-atx-blue',
    },
    {
      key: 'vault',
      label: 'Unified Liquidity Vault',
      sub: 'Principal preserved',
      desc: 'Capital pools into the ULV and generates system yield across multi-surface DeFi strategies.',
      accent: 'text-atx-coral',
    },
    {
      key: 'attribution',
      label: 'AI Attribution Engine',
      sub: 'Conversions verified',
      desc: 'Attribution maps user activity, referrals, and on-chain conversions back to their source.',
      accent: 'text-atx-mesquite',
    },
    {
      key: 'payout',
      label: 'Programmatic Yield Payouts',
      sub: 'Users · Affiliates · Builders',
      desc: 'The vault skims generated yield and streams it to verified actions — never touching principal.',
      accent: 'text-atx-blue',
    },
  ],
} as const

// ─── Three pillars (PillarCardGrid) ─────────────────────────────────────────
export const YPN_PILLARS = {
  eyebrow: 'How it works',
  title: 'Three pillars',
  cards: [
    {
      key: 'ulv',
      index: '01',
      icon: '⬡',
      accent: 'text-atx-blue',
      title: 'Single-sided provisioning',
      subtitle: 'Unified Liquidity Vault (ULV)',
      how: 'Liquidity providers, network-state treasuries, and RWA/DeFi partners deposit capital — primarily single-sided USDC — into Mintware’s Unified Liquidity Vaults.',
      why: 'No paired exposure and no impermanent-loss risk for standard stakers, while capital is pooled efficiently across multi-surface DeFi and real-world-asset strategies.',
    },
    {
      key: 'attribution',
      index: '02',
      icon: '◈',
      accent: 'text-atx-mesquite',
      title: 'AI Attribution Engine',
      subtitle: 'Verified growth, not blind drops',
      how: 'The attribution layer continuously maps user activity, referral networks, growth campaigns, and on-chain conversions back to their origination sources.',
      why: 'Replaces wasteful blind token drops with high-precision performance tracking — every dollar of yield spent is correlated to verified user growth or volume.',
    },
    {
      key: 'distribution',
      index: '03',
      icon: '◉',
      accent: 'text-atx-coral',
      title: 'Automated yield distribution',
      subtitle: 'Non-dilutive marketing budget',
      how: 'The vault is designed to skim generated yield and route it through smart-contract payment streams — rewarding verified user actions, paying referral commissions, and funding active campaigns.',
      why: 'A sustainable marketing budget that refreshes automatically as long as liquidity stays locked — principal is never spent, and the native token is never inflated.',
    },
  ],
} as const

// ─── Value proposition matrix (ValuePropMatrixTable) ────────────────────────
export const YPN_MATRIX = {
  eyebrow: 'Who it’s for',
  title: 'One network, three audiences',
  columns: ['Audience', 'Today’s pain', 'The YPN solution'],
  rows: [
    {
      key: 'treasuries',
      audience: 'Project treasuries',
      pain: 'Draining runway and native tokens on short-lived marketing that leaves nothing behind.',
      solution: 'Self-sustaining acquisition',
      solutionDetail: 'Deposit treasury USDC into the ULV and spend only the generated yield on campaigns. Principal stays untouched.',
      accent: 'text-atx-blue',
    },
    {
      key: 'lps',
      audience: 'Liquidity providers',
      pain: 'Low or volatile yield with no clear real-world utilization of the capital.',
      solution: 'Real yield, plus incentives',
      solutionDetail: 'Earn base yield while contributing to an active ecosystem liquidity layer that powers real growth.',
      accent: 'text-atx-coral',
    },
    {
      key: 'growth',
      audience: 'Growth teams & affiliates',
      pain: 'No attribution and slow, disputed referral payouts.',
      solution: 'Transparent, programmatic payouts',
      solutionDetail: 'AI attribution proves conversions on-chain, so verified actions can trigger programmatic yield payments.',
      accent: 'text-atx-mesquite',
    },
  ],
} as const

// ─── Circle callout (CircleTechBadge) ───────────────────────────────────────
export const YPN_CIRCLE = {
  eyebrow: 'Settlement rail',
  title: 'Designed for Circle’s programmable USDC',
  body: 'The network is built to settle on Circle Programmable Wallets and CCTP (Cross-Chain Transfer Protocol) — friction-free, gas-abstracted USDC deposits and liquidity routing across EVM environments, so treasuries and users interact without managing native gas tokens.',
  points: [
    'Single-sided USDC in, cross-chain via CCTP',
    'Gas-abstracted flows — no native token juggling',
    'Programmable payout streams to verified recipients',
  ],
} as const

// ─── Interactive calculator (YieldCalculatorWidget) ─────────────────────────
// Illustrative estimate only. Monthly Budget = (TVL * APY) / 12.
export const YPN_CALCULATOR = {
  eyebrow: 'Estimate',
  title: 'Your automated campaign budget',
  sub: 'Move the sliders to estimate the monthly marketing budget your yield could fund — while your principal stays fully intact.',
  disclaimer: 'Illustrative estimate only. Not a quote, offer, or guarantee of yield. Actual returns vary with market conditions.',
  tvl: {
    label: 'Treasury deposited (single-sided USDC)',
    min: 100_000,
    max: 25_000_000,
    step: 100_000,
    default: 1_000_000,
  },
  apy: {
    label: 'Estimated annual yield (APY)',
    min: 1,
    max: 20,
    step: 0.5,
    default: 8.0,
  },
  resultLabel: 'Estimated monthly campaign budget',
  principalLabel: 'Principal spent',
  principalValue: '$0 — untouched',
} as const

// ─── Bottom conversion CTA (AppConversionCTA) ───────────────────────────────
export const YPN_CTA = {
  eyebrow: 'Get started',
  title: 'Put your treasury’s yield to work',
  body: 'Connect a wallet or start with just an email — reputation and vaults are keyed to your address either way.',
  primaryCta: 'Launch app',
  secondaryCta: 'Read the docs',
  secondaryHref: '/docs',
} as const

// ─── Home-embed teaser (YieldPaymentNetworkSection) ─────────────────────────
export const YPN_TEASER = {
  eyebrow: '✴ Mintware Yield Payment Network',
  title: 'Fund growth with yield — not your treasury',
  body: 'Park single-sided USDC in a Unified Liquidity Vault, keep your principal intact, and route the yield into attributed user acquisition and campaign payouts.',
  cta: 'Explore the Yield Payment Network',
  href: '/yield-payment-network',
} as const

export type YpnPillar = (typeof YPN_PILLARS.cards)[number]
export type YpnMatrixRow = (typeof YPN_MATRIX.rows)[number]
export type YpnFlowStep = (typeof YPN_FLOW.steps)[number]
